version: "3.8"

services:
  go-app:
    container_name: web-analyzer-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    restart: unless-stopped